### ISSUE TITLE
Will you open source your dataset?

### ISSUE THREAD

**Issue by hustwyk** [tmylla/HackMentor#1]
Thank you for this nice work, I wonder whether the dataset mentioned in the paper, including 14K instructions and 30K conversations, will be open-sourced?

**Comment by tmylla** [comment]
Yes, I will be uploading data to this repository soon. Please note that the quality of the instruction dataset cannot be guaranteed as it has not been manually verified.

**Comment by marcoeg** [comment]
+1. Nice work indeed! Please close this issue once the dataset is uploaded.

**Comment by tmylla** [comment]
The dataset is located in the '/data' directory.
